import path from "path";
import fs from "fs";
import renderRulesTableContent from "./render-rules.ts";

// -----------------------------------------------------------------------------

// eslint-disable-next-line n/no-unsupported-features/node-builtins -- It's only used in script
const dirname = import.meta.dirname;
const readmeFilePath = path.resolve(dirname, "../docs/rules/index.md");
fs.writeFileSync(
  readmeFilePath,
  `---
sidebarDepth: 0
---

# Available Rules

The \`--fix\` option on the [command line](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) automatically fixes problems reported by rules which have a wrench :wrench: below.  
The rules with the following star :star: are included in the \`configs.recommended\` config and the \`configs.standard\` config.

<!-- This file is automatically generated in tools/update-docs-rules-index.js, do not change! -->
${renderRulesTableContent(1)}`,
);
